apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-managed-disk-superset
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-csi
  resources:
    requests:
      storage: 30Gi