apiVersion: v1
kind: Service
metadata:
  name: superset
  labels:
    app: superset
spec:
  ports:
  - name: http
    port: 8088
    targetPort: 8088
  selector:
    app: superset
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: superset-deployment
spec:
  selector:
    matchLabels:
      app: superset
  template:
    metadata:
      labels:
        app: superset
    spec:
      containers:
      - env:
        - name: DB_HOST
          value: engage-poc-dev-pg3.postgres.database.azure.com
        - name: REDIS_HOST
          value: 10.224.0.4
        - name: POSTGRES_USER
          value: "postgres@engage-poc-dev-pg3"
        - name: POSTGRES_PASSWORD
          value: engage123!
        - name: DB_NAME
          value: postgres
        - name: DB_SCHEMA
          value: superset  
        - name: SUPERSET_FEATURE_EMBEDDED_SUPERSET
          value: "true"
        - name: PYTHONPATH
          value: "${PYTHONPATH}:/home/superset/superset/"
        image: amancevice/superset:latest
        name: superset
        ports:
        - containerPort: 8088
        volumeMounts:
        - mountPath: /home/superset/superset
          name: superset-config 
      volumes:
      - name: superset-config
        configMap:
          name: superset-config
